//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stol
    {
        public int ID_stol { get; set; }
        public string opis { get; set; }
        public string status { get; set; }
        public Nullable<int> ID_korisnika { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
    }
}
